// Reads divergent ASTs from prior fuzz runs (multi-seed + big-sweep), dedupes
// by canonicalKey, classifies each by AST shape features, and emits a markdown
// report for triage.

import {readFileSync, writeFileSync} from 'node:fs';

type Entry = {
  canonicalKey: string;
  astHash: string;
  ast: any;
  sourceFile: string;
};

function parseLog(path: string): Entry[] {
  const lines = readFileSync(path, 'utf8').split('\n');
  const out: Entry[] = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const m = line.match(
      /^\s+- ([0-9a-f]+): unexpected divergence \(canonicalKey=([0-9a-f]+)\)/,
    );
    if (!m) continue;
    const next = lines[i + 1] ?? '';
    const astMatch = next.match(/^\s+AST: (.+)$/);
    if (!astMatch) continue;
    let ast;
    try {
      ast = JSON.parse(astMatch[1]);
    } catch {
      continue;
    }
    out.push({astHash: m[1], canonicalKey: m[2], ast, sourceFile: path});
  }
  return out;
}

const all = [
  ...parseLog('/tmp/multi-seed-fuzz.log'),
  ...parseLog('/tmp/big-sweep.log'),
];

const byKey = new Map<string, Entry>();
for (const e of all) {
  if (!byKey.has(e.canonicalKey)) byKey.set(e.canonicalKey, e);
}

function classify(ast: any): {bucket: string; features: string[]} {
  const s = JSON.stringify(ast);
  const features: string[] = [];

  const hasOr = s.includes('"type":"or"');
  const hasAnd = s.includes('"type":"and"');
  const hasExists = s.includes('correlatedSubquery');
  const hasNotExists = s.includes('"NOT EXISTS"');
  const orCount = (s.match(/"type":"or"/g) ?? []).length;
  const andCount = (s.match(/"type":"and"/g) ?? []).length;
  const existsCount = (s.match(/correlatedSubquery/g) ?? []).length;
  const hasStart = s.includes('"start":');
  const hasLimit = s.includes('"limit":');
  const hasOrderBy = s.includes('"orderBy":');
  const hasRelated = s.includes('"related":[{');
  const hasNestedExists =
    ast.where && JSON.stringify(ast.where).includes('"related"');
  const hasIsNull = s.includes('"op":"IS"');
  const hasNotIn =
    s.includes('"NOT IN"') ||
    s.includes('"NOT LIKE"') ||
    s.includes('"NOT ILIKE"');
  const hasFlip = s.includes('"flip":');
  const hasScalar = s.includes('"scalar":');

  if (hasOr) features.push(`or(${orCount})`);
  if (hasAnd) features.push(`and(${andCount})`);
  if (hasExists) features.push(`exists(${existsCount})`);
  if (hasNotExists) features.push('not_exists');
  if (hasStart) features.push('start');
  if (hasLimit) features.push('limit');
  if (hasOrderBy) features.push('orderBy');
  if (hasRelated) features.push('related[]');
  if (hasIsNull) features.push('IS NULL');
  if (hasNotIn) features.push('NOT IN/LIKE');
  if (hasFlip) features.push('flip');
  if (hasScalar) features.push('scalar');

  // Categorize into one primary bucket
  let bucket: string;
  if (orCount >= 2 && hasExists) bucket = 'A. nested-OR with EXISTS';
  else if (hasOr && hasAnd && hasExists) bucket = 'B. OR-of-AND-of-EXISTS';
  else if (hasOr && hasExists && existsCount >= 2)
    bucket = 'C. OR with multiple EXISTS branches';
  else if (hasOr && hasExists) bucket = 'D. simple OR-with-EXISTS';
  else if (hasAnd && hasExists) bucket = 'E. AND-with-EXISTS (no OR)';
  else if (hasExists) bucket = 'F. plain EXISTS';
  else bucket = 'G. no-EXISTS divergence';
  return {bucket, features};
}

const buckets = new Map<string, Entry[]>();
for (const e of byKey.values()) {
  const {bucket} = classify(e.ast);
  if (!buckets.has(bucket)) buckets.set(bucket, []);
  buckets.get(bucket)!.push(e);
}

const lines: string[] = [];
lines.push('# Rust IVM Parity Divergences — Categorized');
lines.push('');
lines.push(`Total unique divergent shapes: **${byKey.size}**`);
lines.push('');
lines.push('Generated by aggregating two fuzz runs:');
lines.push(
  '- 15 seeds × 500 iter (default endOnFailure mode) → 15 unique shapes',
);
lines.push(
  '- 1 seed × 5000 iter (FUZZ_KEEP_GOING=1) → 11 unique shapes (3 overlap with multi-seed)',
);
lines.push('');
lines.push('## Bucket distribution');
lines.push('');
lines.push('| Bucket | Count | Description |');
lines.push('|---|---|---|');
const bucketDescs: Record<string, string> = {
  'A. nested-OR with EXISTS':
    'OR clauses nested inside OR clauses, at least one EXISTS branch',
  'B. OR-of-AND-of-EXISTS': 'OR with AND subbranches that contain EXISTS',
  'C. OR with multiple EXISTS branches':
    'Top-level OR with ≥2 EXISTS subqueries',
  'D. simple OR-with-EXISTS': 'Single OR with one EXISTS branch',
  'E. AND-with-EXISTS (no OR)': 'AND of conditions including EXISTS, no OR',
  'F. plain EXISTS': 'EXISTS as the only condition',
  'G. no-EXISTS divergence':
    'Divergence without any correlatedSubquery — interesting outlier',
};
for (const [bucket, entries] of [...buckets.entries()].sort()) {
  lines.push(
    `| ${bucket} | ${entries.length} | ${bucketDescs[bucket] ?? ''} |`,
  );
}

lines.push('');
lines.push('## Per-shape detail');
lines.push('');

for (const [bucket, entries] of [...buckets.entries()].sort()) {
  lines.push(`### ${bucket} (${entries.length})`);
  lines.push('');
  for (const e of entries) {
    const {features} = classify(e.ast);
    lines.push(`#### \`${e.canonicalKey}\``);
    lines.push('');
    lines.push(`- root table: \`${e.ast.table}\``);
    lines.push(`- features: ${features.join(', ')}`);
    lines.push(`- AST hash: \`${e.astHash}\``);
    lines.push('');
    lines.push('```json');
    lines.push(JSON.stringify(e.ast, null, 2));
    lines.push('```');
    lines.push('');
  }
}

const out = lines.join('\n');
writeFileSync('PARITY-DIVERGENCES-CATALOG.md', out);
console.log(
  `Wrote PARITY-DIVERGENCES-CATALOG.md with ${byKey.size} unique shapes across ${buckets.size} buckets`,
);
for (const [bucket, entries] of [...buckets.entries()].sort()) {
  console.log(`  ${bucket}: ${entries.length}`);
}
