/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Pipeline {
  static build(configJson: string): Pipeline;
  fetch(requestJson: string): string;
  push(changeJson: string): string;
}

export declare class RustFilterPredicate {
  constructor(predicateJson: string);
  /**
   * Evaluate a single row (as a JS object) against the predicate.
   * Returns true if the row passes the filter.
   */
  evaluateRow(row: object): boolean;
  /**
   * Filter a batch of changes. Returns which pass and which edits need splitting.
   *
   * Changes are JS arrays: [type, node, oldNode/childData/null]
   * Node is: { row: {...}, relationships: {...} }
   * We only read node.row fields referenced by the predicate.
   */
  filterPushBatch(changes: object): FilterResult;
}

/**
 * Generic key-value storage backed by a Rust HashMap.
 * Stores raw JSON strings — no parsing or validation.
 */
export declare class RustStorage {
  constructor();
  get(key: string): string | null;
  set(key: string, value: string): void;
  del(key: string): void;
  /** Scan all keys with a given prefix. Returns array of [key, value] pairs. */
  scan(prefix: string): Array<Array<string>>;
  clear(): void;
  size(): number;
}

export declare class RustTakeState {
  constructor(sortJson: string);
  /** Returns JSON string of TakeState or null */
  getState(key: string): string | null;
  setState(key: string, stateJson: string): void;
  delState(key: string): void;
  getMaxBound(): string | null;
  setMaxBound(boundJson: string): void;
  clearMaxBound(): void;
  /** Compare two rows using the sort spec. Returns -1, 0, or 1. */
  compareRows(aJson: string, bJson: string): number;
  /** Batch operation: set state + conditionally update max bound in one call */
  setStateAndMaybeUpdateMax(key: string, stateJson: string): void;
  /** Clear all state (for destroy/reset) */
  clear(): void;
  /** Get the number of states stored */
  size(): number;
}

export interface EditSplitInfo {
  index: number;
  splitType: EditSplitType;
}

/** Result of filtering an edit change */
export declare const enum EditSplitType {
  /** Old matched, new matches → pass through as edit */
  Both = 'Both',
  /** Old matched, new doesn't → emit as remove (of old node) */
  Remove = 'Remove',
  /** Old didn't match, new does → emit as add (of new node) */
  Add = 'Add',
}

export interface FilterResult {
  /** Indices of changes that pass through unchanged */
  passed: Array<number>;
  /** Edit changes that need splitting */
  splits: Array<EditSplitInfo>;
}

export declare function rustBuildJoinConstraint(
  sourceRowJson: string,
  sourceKey: Array<string>,
  targetKey: Array<string>,
): string | null;

/**
 * Batch decision function for Exists operator push path.
 * Takes JSON array of change descriptors, returns JSON array of action descriptors.
 */
export declare function rustExistsPushBatch(
  changesJson: string,
  relationshipName: string,
  notExists: boolean,
): string;

export declare function rustIsJoinMatch(
  parentRowJson: string,
  parentKey: Array<string>,
  childRowJson: string,
  childKey: Array<string>,
): boolean;

/**
 * Batch function for the pushChildChange hot path.
 * Combines constraint building + batch matching in a single napi call.
 */
export declare function rustJoinPushChildBatch(
  childRowJson: string,
  childKey: Array<string>,
  parentKey: Array<string>,
  parentRowsJson: Array<string>,
): string;

export declare function rustRowEqualsForCompoundKey(
  aJson: string,
  bJson: string,
  key: Array<string>,
): boolean;
